package pdf

import (
	"strconv"
	"time"

	"github.com/fhedul/amaarshop/backend/internal/domain"
)

// OrdersExportData is what BuildOrdersExport needs to render a seller orders PDF.
type OrdersExportData struct {
	Shop   *domain.Shop
	Orders []*domain.Order
	From   time.Time // optional — left as zero value if not filtered
	To     time.Time
	Status string
}

// BuildOrdersExport renders a seller-facing list of orders. One row per order.
func BuildOrdersExport(in OrdersExportData) ([]byte, error) {
	d := New()
	d.Header(in.Shop.Name, "Orders export")
	d.H1("Orders")

	// Filter description line so the seller knows what's in the file.
	desc := "Showing all orders"
	if !in.From.IsZero() && !in.To.IsZero() {
		desc = "From " + in.From.Format("02 Jan 2006") + " to " + in.To.Format("02 Jan 2006")
	}
	if in.Status != "" {
		desc += "  ·  status: " + in.Status
	}
	desc += "  ·  " + strconv.Itoa(len(in.Orders)) + " row(s)"
	d.Body(desc)
	d.Spacer(2)

	rows := make([][]string, 0, len(in.Orders))
	totalsBDT := 0.0
	for _, o := range in.Orders {
		amt, _ := strconv.ParseFloat(o.TotalBDT, 64)
		if o.Status != "cancelled" {
			totalsBDT += amt
		}
		rows = append(rows, []string{
			"#" + shortRef(o.ID),
			o.CreatedAt.Format("02 Jan 2006"),
			o.CustomerName,
			o.CustomerPhone,
			o.DeliveryArea,
			capitalize(o.Status),
			"BDT " + o.TotalBDT,
		})
	}
	d.Table([]Column{
		{Header: "Order",     Width: 22, Align: "L"},
		{Header: "Date",      Width: 24, Align: "L"},
		{Header: "Customer",  Width: 0,  Align: "L"},
		{Header: "Phone",     Width: 28, Align: "L"},
		{Header: "Area",      Width: 22, Align: "L"},
		{Header: "Status",    Width: 22, Align: "L"},
		{Header: "Total",     Width: 24, Align: "R"},
	}, rows)

	d.Spacer(4)
	d.TotalsBlock([][]string{
		{"Orders", strconv.Itoa(len(in.Orders))},
		{"Net revenue", "BDT " + strconv.FormatFloat(totalsBDT, 'f', 2, 64)},
	})

	d.Footer(
		"Generated by AmaarShop on "+time.Now().Format("02 Jan 2006, 15:04"),
		"Confidential — for "+in.Shop.Name+" only",
	)
	return d.Bytes()
}

// ProductsExportData drives BuildProductsExport.
type ProductsExportData struct {
	Shop     *domain.Shop
	Products []*domain.Product
}

// BuildProductsExport renders the seller's catalog as a PDF.
func BuildProductsExport(in ProductsExportData) ([]byte, error) {
	d := New()
	d.Header(in.Shop.Name, "Catalog export")
	d.H1("Products")
	d.Body(strconv.Itoa(len(in.Products)) + " products in this catalog (excluding archived).")
	d.Spacer(2)

	rows := make([][]string, 0, len(in.Products))
	for _, p := range in.Products {
		visibility := "Live"
		if !p.IsActive {
			visibility = "Hidden"
		}
		if p.IsArchived {
			visibility = "Archived"
		}
		rows = append(rows, []string{
			p.Name,
			"BDT " + p.PriceBDT,
			strconv.Itoa(p.Stock),
			visibility,
		})
	}
	d.Table([]Column{
		{Header: "Product",    Width: 0,  Align: "L"},
		{Header: "Price",      Width: 28, Align: "R"},
		{Header: "Stock",      Width: 22, Align: "R"},
		{Header: "Visibility", Width: 24, Align: "L"},
	}, rows)

	d.Footer(
		"Generated by AmaarShop on "+time.Now().Format("02 Jan 2006, 15:04"),
		"Confidential — for "+in.Shop.Name+" only",
	)
	return d.Bytes()
}
